# Generated by Django 3.0.6 on 2020-05-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenrateInvoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceNO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billno', models.IntegerField(max_length=100)),
            ],
            options={
                'db_table': 'invoiceno',
            },
        ),
    ]
