# Generated by Django 3.0.6 on 2020-05-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenrateInvoice', '0002_invoiceno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceno',
            name='billno',
            field=models.IntegerField(),
        ),
    ]
